In [0]:
'''
This notebook uses best algorithm with best hyper parameter to train a model. Tpot script is used to determine best algorithm with best hyper parameter
'''

In [0]:
import numpy as np
import pandas as pd
import pickle
import joblib
from sklearn.decomposition import PCA
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline

In [0]:
# NOTE: Make sure that the outcome column is labeled 'target' in the data file
tpot_data = pd.read_csv('/content/drive/My Drive/3kImages/TrainFeatures.csv', sep=',')
print(tpot_data['label'].head().to_string())
print(tpot_data.columns)
features = tpot_data.drop('label', axis=1)
print(features.head())
training_features, testing_features, training_target, testing_target = \
            train_test_split(features, tpot_data['label'], random_state=None)

# This below pipeline has been referenced from Tpot classifier result.
exported_pipeline = make_pipeline(
    PCA(iterated_power=3, svd_solver="randomized"),
    GradientBoostingClassifier(learning_rate=0.1, max_depth=9, max_features=0.8500000000000001, min_samples_leaf=3, min_samples_split=14, n_estimators=100, subsample=0.7000000000000001)
)

exported_pipeline.fit(training_features, training_target)
results = exported_pipeline.predict(testing_features)


0    0
1    0
2    0
3    0
4    0
Index(['feat0', 'feat1', 'feat2', 'feat3', 'feat4', 'feat5', 'feat6', 'feat7',
       'feat8', 'feat9', 'feat10', 'feat11', 'feat12', 'feat13', 'feat14',
       'feat15', 'feat16', 'feat17', 'feat18', 'feat19', 'feat20', 'feat21',
       'feat22', 'feat23', 'feat24', 'feat25', 'feat26', 'feat27', 'feat28',
       'feat29', 'feat30', 'feat31', 'feat32', 'feat33', 'feat34', 'feat35',
       'feat36', 'label'],
      dtype='object')
   feat0     feat1     feat2     feat3  ...    feat33    feat34    feat35    feat36
0      0 -0.640462 -0.521255 -0.449796  ... -0.044576 -0.148538 -0.679705 -0.792991
1      0 -0.377174  0.306400  0.019787  ...  0.696833  0.273349 -0.006564  0.177287
2      0 -0.768174 -0.156048 -0.377661  ...  0.093005 -0.426083 -0.205605 -0.502266
3      0 -0.464109  0.271042 -0.035375  ...  0.678998 -0.493622  0.191535 -0.151855
4      0 -0.378830 -0.012883 -0.073564  ...  0.775814 -0.290864 -0.104640 -0.300253

[5 rows x 37 columns]


In [0]:
print(results)

[0 0 0 ... 0 2 0]


In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
#SAVING 
with open('/content/drive/My Drive/tpotexport/dump.pkl', 'wb') as f:
  pickle.dump(exported_pipeline, f)

In [0]:
##LOADING 
clf2 = joblib.load('/content/drive/My Drive/3kImages/tpotexport/dump.pkl')
preds2 = clf2.predict(training_features)
print(preds2)

[0 2 2 ... 0 2 2]


In [0]:
clf2.score(testing_features, testing_target)

0.9666814749000444

In [0]:
test = pd.read_csv('/content/drive/My Drive/3kImages/TestFeatures.csv', sep=',')
print(test['label'].head().to_string())
print(test.columns)
features = tpot_data.drop('label', axis=1)
print(features.head())
training_features, testing_features, training_target, testing_target = \
            train_test_split(features, tpot_data['label'], random_state=None)


training_testing_Features =  training_features + testing_features
training_testing_Targets = training_target + testing_target

0    0
1    0
2    0
3    0
4    0
Index(['feat0', 'feat1', 'feat2', 'feat3', 'feat4', 'feat5', 'feat6', 'feat7',
       'feat8', 'feat9', 'feat10', 'feat11', 'feat12', 'feat13', 'feat14',
       'feat15', 'feat16', 'feat17', 'feat18', 'feat19', 'feat20', 'feat21',
       'feat22', 'feat23', 'feat24', 'feat25', 'feat26', 'feat27', 'feat28',
       'feat29', 'feat30', 'feat31', 'feat32', 'feat33', 'feat34', 'feat35',
       'feat36', 'label'],
      dtype='object')
   feat0     feat1     feat2     feat3  ...    feat33    feat34    feat35    feat36
0      0 -0.640462 -0.521255 -0.449796  ... -0.044576 -0.148538 -0.679705 -0.792991
1      0 -0.377174  0.306400  0.019787  ...  0.696833  0.273349 -0.006564  0.177287
2      0 -0.768174 -0.156048 -0.377661  ...  0.093005 -0.426083 -0.205605 -0.502266
3      0 -0.464109  0.271042 -0.035375  ...  0.678998 -0.493622  0.191535 -0.151855
4      0 -0.378830 -0.012883 -0.073564  ...  0.775814 -0.290864 -0.104640 -0.300253

[5 rows x 37 columns]


In [0]:
clf2.score(testing_features, testing_target)

0.9666814749000444

In [0]:
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
#clf2.fit(testing_features, testing_target)


predictions = clf2.predict(testing_features)

print("Confusion Matrix:")
print(confusion_matrix(testing_target, predictions))
print()
print("Classification Report")
print(classification_report(testing_target, predictions))

Confusion Matrix:
[[1001    0   24]
 [   2  234    0]
 [  49    0  941]]

Classification Report
              precision    recall  f1-score   support

           0       0.95      0.98      0.96      1025
           1       1.00      0.99      1.00       236
           2       0.98      0.95      0.96       990

    accuracy                           0.97      2251
   macro avg       0.98      0.97      0.97      2251
weighted avg       0.97      0.97      0.97      2251



In [0]:
#ONLINE PICS
#blurry image
import matplotlib.pyplot as plt

!wget https://boofcv.org/images/thumb/6/6c/Kodim17_face_gaussian.jpg/250px-Kodim17_face_gaussian.jpg
img = img_as_float(io.imread('250px-Kodim17_face_gaussian.jpg'))
score = brisque.calculate_features(img, 7, 7 / 6)
print(loaded_svm.predict([score]))
plt.imshow(img)

In [0]:
#macroblocking image samples
!wget https://upload.wikimedia.org/wikipedia/commons/e/e9/Felis_silvestris_silvestris_small_gradual_decrease_of_quality.png
img = img_as_float(io.imread('Felis_silvestris_silvestris_small_gradual_decrease_of_quality.png'))
score = brisque.calculate_features(img, 7, 7 / 6)
print(loaded_svm.predict([score]))
plt.imshow(img)