In [ ]:
'''
        ***** Image Classification with TensorFlow for Cat/Dog Use case********

In this notebook, 
A. Used local data of Cat/Dog image to build Image classification model using TensorFlow library (CNN)
B. For referencing Image data, there are different ways of providing a reference of Image data such as 
    a. via 'flow_from_directory' api  - This is used when you have two different folder for Train and Validation images
    b. via 'flow_from_dataframe' api - This is used when u have single folder and u load the images into dataframe and then split
        into Train and Validation image

C. In this notebook implementation, 
    a. 'flow_from_directory' api is used to load the data from local directory and used it in model fitting
    
D. Save the model and model weight into file and used these files for further prediction on Test Images
   
'''

In [11]:
# Importing the Keras libraries and packages
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model
from tensorflow.keras import utils

In [28]:
# Part-1 - Initialising the CNN and compiling the model
classifier = Sequential()

# Step 1 - Convolution
classifier.add(Conv2D(32, (3, 3), input_shape = (64, 64, 3), activation = 'relu'))

# Step 2 - Pooling
classifier.add(MaxPooling2D(pool_size = (2, 2)))

# Adding a second convolutional layer
classifier.add(Conv2D(32, (3, 3), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2, 2)))

# Step 3 - Flattening
classifier.add(Flatten())

# Step 4 - Full connection
classifier.add(Dense(units = 128, activation = 'relu'))
classifier.add(Dense(units = 1, activation = 'sigmoid'))

# Compiling the CNN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [29]:
# Part 2 - Create train and test ImageDataGenerator via 'flow_from_directory' 

train_datagen = ImageDataGenerator(rescale = 1./255, shear_range = 0.2, zoom_range = 0.2, horizontal_flip = True)
print(train_datagen)

training_set = train_datagen.flow_from_directory('Downloads/trainsubset', target_size = (64, 64), 
                                                 batch_size = 32, class_mode = 'binary')

Found 210 images belonging to 2 classes.


In [30]:
test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('Downloads/testsubset', target_size = (64, 64), 
                                            batch_size = 32, class_mode = 'binary')

Found 132 images belonging to 2 classes.


In [32]:
# Part 3 - Fitting the CNN to the images. Train the Model on Training images. For validation, used Test Images

classifier.fit_generator(training_set, steps_per_epoch = 8000, epochs = 25,
                         validation_data = test_set, validation_steps = 2000)

Epoch 1/25
8000/8000 [==============================] - 1351s 169ms/step - loss: 0.0197 - acc: 0.9919 - val_loss: 6.2451 - val_acc: 0.4848
Epoch 2/25
8000/8000 [==============================] - 1348s 169ms/step - loss: 7.7223e-06 - acc: 1.0000 - val_loss: 8.4396 - val_acc: 0.4621
Epoch 3/25
8000/8000 [==============================] - 1348s 168ms/step - loss: 6.1360e-08 - acc: 1.0000 - val_loss: 10.3973 - val_acc: 0.4773
Epoch 4/25
8000/8000 [==============================] - 1343s 168ms/step - loss: 0.0014 - acc: 0.9997 - val_loss: 8.9769 - val_acc: 0.5076
Epoch 5/25
8000/8000 [==============================] - 1338s 167ms/step - loss: 0.0013 - acc: 0.9996 - val_loss: 9.5480 - val_acc: 0.5303
Epoch 6/25
8000/8000 [==============================] - 1339s 167ms/step - loss: 4.0490e-07 - acc: 1.0000 - val_loss: 11.2074 - val_acc: 0.5455
Epoch 7/25
8000/8000 [==============================] - 1335s 167ms/step - loss: 0.0020 - acc: 0.9996 - val_loss: 11.4909 - val_acc: 0.4394
Epoch 8/25
8

In [33]:
# Part 4 - Making new predictions for single image which is loaded from local folder

test_image = image.load_img('Downloads/11221.jpg', target_size = (64, 64))
test_image = image.img_to_array(test_image)
print("test image1:", test_image)
test_image = np.expand_dims(test_image, axis = 0)
print("test image2:", test_image)


result = classifier.predict(test_image)
training_set.class_indices
if result[0][0] == 1:
    prediction = 'dog'
else:
    prediction = 'cat'
    
print("It is a :", prediction)

test image1: [[[ 40.  84. 111.]
  [ 40.  86. 112.]
  [ 42.  91. 121.]
  ...
  [ 93.  23.  13.]
  [ 32.  18.   5.]
  [ 26.  11.  14.]]

 [[ 53.  75.  88.]
  [ 41.  88. 116.]
  [ 45.  90. 113.]
  ...
  [ 68.  15.  11.]
  [ 18.  15.   6.]
  [ 23.  13.  14.]]

 [[ 11.   0.   0.]
  [ 50.  90. 116.]
  [ 43.  91. 113.]
  ...
  [ 58.  17.  13.]
  [ 13.  15.   2.]
  [ 21.   9.  11.]]

 ...

 [[ 61.  26.  33.]
  [ 54.  19.  26.]
  [ 59.  24.  31.]
  ...
  [137.  73.  38.]
  [133.  68.  36.]
  [136.  71.  43.]]

 [[ 50.  17.  24.]
  [ 61.  26.  33.]
  [ 60.  23.  31.]
  ...
  [137.  68.  35.]
  [126.  60.  26.]
  [123.  60.  27.]]

 [[ 62.  31.  37.]
  [ 74.  32.  42.]
  [ 72.  24.  36.]
  ...
  [147.  77.  51.]
  [134.  67.  38.]
  [136.  74.  37.]]]
test image2: [[[[ 40.  84. 111.]
   [ 40.  86. 112.]
   [ 42.  91. 121.]
   ...
   [ 93.  23.  13.]
   [ 32.  18.   5.]
   [ 26.  11.  14.]]

  [[ 53.  75.  88.]
   [ 41.  88. 116.]
   [ 45.  90. 113.]
   ...
   [ 68.  15.  11.]
   [ 18.  15.   6.]


In [34]:
# Part 5- save model file and model weights 
classifier.save("classifier.model1")
classifier.save_weights("classifier.model2")
print("Saved classifier model to disk")

Saved classifier model to disk


In [35]:
# Part 6-  serialize model to JSON
classifier_json = classifier.to_json()

with open("classifier.json", "w") as json_file:
    json_file.write(classifier_json)

In [38]:
# Part 7- Load the model file and used it for prediction on test image.
classnames = ["cat", "dog"]
model = load_model('classifier.model1')

test_image = image.load_img('Downloads/10212.jpg', target_size = (64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = model.predict(test_image)
training_set.class_indices
if result[0][0] == 1:
    prediction = 'dog'
else:
    prediction = 'cat'
print("It is a :", prediction)

It is a : cat
